/**
 * This configuration was generated using the CKEditor 5 Builder. You can modify it anytime using this link:
 * https://ckeditor.com/ckeditor-5/builder/#installation/NoDgNARATAdAnDAjBSBWKBmA7NuiAMOAbBvoogCxFFSVH75VFaJapxEGoEMgoQAHAC4oMYYIjCTpUsPgC6kCgCMMAUxUATCPKA==
 */

import "ckeditor5/ckeditor5.css";

import {
  Alignment,
  AutoImage,
  Autoformat,
  Autosave,
  BalloonToolbar,
  BlockQuote,
  BlockToolbar,
  Bold,
  CloudServices,
  DecoupledEditor,
  Emoji,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Fullscreen,
  Heading,
  HorizontalLine,
  ImageBlock,
  ImageCaption,
  ImageEditing,
  ImageInline,
  ImageInsertViaUrl,
  ImageResize,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  ImageUtils,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  MediaEmbed,
  Mention,
  Paragraph,
  PlainTableOutput,
  SimpleUploadAdapter,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableProperties,
  TableToolbar,
  TextTransformation,
  TodoList,
  Underline,
} from "ckeditor5";

// Custom plugins
import CustomFontFamilyUI from "./custom-plugins/custom-font-ui/src/CustomFontFamilyUI.js";
import CustomFontSizeUI from "./custom-plugins/custom-font-ui/src/CustomFontSizeUI.js";
import GeminiEditing from "./custom-plugins/gemini/geminiediting.js";
import GeminiUI from "./custom-plugins/gemini/geminiui.js";
import Placeholder from "./custom-plugins/placeholder/src/Placeholder.js";

import translations from "ckeditor5/translations/pt.js";
import "./custom-translations.js";

export default class CustomDecoupledEditor extends DecoupledEditor {
  /**
   * Create a free account with a trial: https://portal.ckeditor.com/checkout?plan=free
   */
  static LICENSE_KEY = "GPL"; // or <YOUR_LICENSE_KEY>.

  static editorConfig = {
    toolbar: {
      items: [
        "undo",
        "redo",
        "|",
        "fontFamilyDropdown",
        "|",
        "fontSizeDropdown",
        "|",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "bold",
        "italic",
        "underline",
        "|",
        "alignment:left",
        "alignment:center",
        "alignment:right",
        "alignment:justify",
        "|",
        "link",
        "insertTable",
        "blockQuote",
        "|",
        "gemini",
        "placeholder",
        "|",
        "imageUpload",
        "|",
        "bulletedList",
        "numberedList",
        "todoList",
        "outdent",
        "indent",
      ],
      shouldNotGroupWhenFull: false,
    },
    plugins: [
      Alignment,
      Autoformat,
      AutoImage,
      Autosave,
      BalloonToolbar,
      BlockQuote,
      BlockToolbar,
      Bold,
      CloudServices,
      Emoji,
      Essentials,
      FontBackgroundColor,
      FontColor,
      FontFamily,
      FontSize,
      Fullscreen,
      HorizontalLine,
      ImageBlock,
      ImageCaption,
      ImageEditing,
      ImageResize,
      ImageInline,
      ImageInsertViaUrl,
      ImageStyle,
      ImageTextAlternative,
      ImageToolbar,
      ImageUpload,
      ImageUtils,
      Indent,
      IndentBlock,
      Italic,
      Link,
      LinkImage,
      List,
      MediaEmbed,
      Mention,
      Paragraph,
      PlainTableOutput,
      Strikethrough,
      Subscript,
      Superscript,
      Table,
      TableCaption,
      TableToolbar,
      TableCellProperties,
      TableProperties,
      TextTransformation,
      TodoList,
      Underline,
      Heading,
      SimpleUploadAdapter,

      // Custom
      CustomFontSizeUI,
      CustomFontFamilyUI,
      Placeholder,
      GeminiEditing,
      GeminiUI,
    ],
    balloonToolbar: [
      "bold",
      "italic",
      "|",
      "link",
      "|",
      "bulletedList",
      "numberedList",
    ],
    blockToolbar: [
      "|",
      "fontFamilyDropdown",
      "|",
      "fontSizeDropdown",
      "|",
      "fontColor",
      "fontBackgroundColor",
      "|",
      "bold",
      "italic",
      "|",
      "link",
      "insertTable",
      "|",
      "bulletedList",
      "numberedList",
      "outdent",
      "indent",
    ],
    fontFamily: {
      options: [
        "Arial",
        "Courier New",
        "Georgia",
        "Lucida Sans Unicode",
        "Tahoma",
        "Times New Roman",
        "Trebuchet MS",
        "Verdana",
      ],
    },
    fontSize: {
      options: [
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "18",
        "20",
        "22",
        "24",
        "26",
        "28",
        "36",
        "48",
      ].map((val) => ({
        model: parseInt(val),
        title: val,
        view: {
          name: "span",
          styles: {
            "font-size": `${val}pt`,
          },
        },
      })),
    },
    fullscreen: {
      onEnterCallback: (container) =>
        container.classList.add(
          "editor-container",
          "editor-container_document-editor",
          "editor-container_include-fullscreen",
          "main-container",
        ),
    },
    image: {
      toolbar: [
        "toggleImageCaption",
        "imageTextAlternative",
        "|",
        "imageStyle:inline",
        "imageStyle:wrapText",
        "imageStyle:breakText",
      ],
    },
    language: "pt",
    licenseKey: CustomDecoupledEditor.LICENSE_KEY,
    link: {
      addTargetToExternalLinks: true,
      defaultProtocol: "https://",
      decorators: {
        toggleDownloadable: {
          mode: "manual",
          label: "Downloadable",
          attributes: {
            download: "file",
          },
        },
      },
    },
    mention: {
      feeds: [
        {
          marker: "@",
          feed: [
            /* See: https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html */
          ],
        },
      ],
    },
    placeholder: "Digite ou cole o seu conteúdo aqui.",
    table: {
      contentToolbar: [
        "tableColumn",
        "tableRow",
        "mergeTableCells",
        "tableCellProperties",
        "tableProperties",
      ],
    },
    translations: [translations],
  };
}
